services:
  # ========== DATABASE (Her zaman çalışır) ==========
  protectedpayment.database:
    environment:
      - POSTGRES_DB=protectedPaymentApp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
