@ProtectedPayment.Order.API_HostAddress = https://localhost:5301

### GetOrders

GET {{ProtectedPayment.Order.API_HostAddress}}/orders/
Accept: application/json

### CreateOrder

POST {{ProtectedPayment.Order.API_HostAddress}}/orders/
Content-Type: application/json

{
  "productName": "Samsung 92",
  "amount": 120000
}

### CancelOrder

POST {{ProtectedPayment.Order.API_HostAddress}}/orders/019c0488-192a-72e8-9184-4acf40a4c204/cancel
Content-Type: application/json
