@ProtectedPayment.Order.API_HostAddress = https://localhost:5301

### GetOrders

GET {{ProtectedPayment.Order.API_HostAddress}}/orders/
Accept: application/json

### CreateOrder

POST {{ProtectedPayment.Order.API_HostAddress}}/orders/
Content-Type: application/json

{
  "productName": "Caretta 35",
  "amount": 120000
}

### CancelOrder

POST {{ProtectedPayment.Order.API_HostAddress}}/orders/019c0b09-2a8d-7253-a764-cba699f01d5f/cancel
Content-Type: application/json
