@ProtectedPayment.Order.API_HostAddress = https://localhost:5301

### GetOrders

GET {{ProtectedPayment.Order.API_HostAddress}}/orders/
Accept: application/json

### CreateOrder

POST {{ProtectedPayment.Order.API_HostAddress}}/orders/
Content-Type: application/json

{
  "productName": "Honda Civic Vtec Sağ Far",
  "amount": 120000
}

### CancelOrder

POST {{ProtectedPayment.Order.API_HostAddress}}/orders/019c0bd7-2368-7c43-a703-c16761405ab3/cancel
Content-Type: application/json
